# -*- coding: utf-8 -*-
"""exam5thsem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AdTlKX271fYq3nQDa3IJWlC5co6mCFeR
"""

import pandas as pd
import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score

data=fetch_california_housing()
print(data)

df=pd.DataFrame(data.data,columns=data.feature_names)
df['PRICE']=data.target
df.describe()
df.shape
df.info()
df.isnull().sum()

x=df.drop('PRICE',axis=1)
y=df['PRICE']
x
y

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=4)
x_train
y_train

model=LinearRegression()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
y_pred

mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
print("Mean Squared Error=",mse)
print("R2 Score=",r2)